chopstick/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('',views.home,name="home"),
    path('dishes/', include('dishes.urls')),
    path('food_section/', include('food_section.urls')),
    path('customer/', include('customer.urls')),
    path('orders/', include('orders.urls')),
    path('outlet/', include('outlet.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dishes/urls.py
from django.urls import include, path
from dishes.views import *

app_name = 'dishes'

urlpatterns = [
path('all_dishes/<int:pk>/<int:pk1>',all_dishes,name='all_dishes'),

path('menu/<int:pk>',menu,name='menu'),

path('add_dishes/<int:pk>/<int:pk1>',add_dishes,name='add_dishes'),

path('update_dish/<int:pk>/<int:pk1>/<int:pk2>',update_dish,name='update_dish'),

path('delete_dish/<int:pk>/<int:pk1>/<int:pk2>',delete_dish,name='delete_dish'),

]

food_section/urls.py
from django.urls import include, path
from food_section.views import *

app_name = 'food_section'

urlpatterns = [

path('food_add/<int:pk>',food_add,name='food_add'),

path('food_section_master/<int:pk>',food_section_master,name='food_section_master'),

path('food__section_update/<int:pk>/<int:pk1>',food__section_update,name='food__section_update'),

]

food_section/models.py
from django.db import models
from outlet.models import outlet

# Create your models here.
class food_section(models.Model):
    section_name = models.CharField(max_length=50)
    outlet_id = models.ForeignKey(outlet,on_delete=models.CASCADE,default=1)
    is_active  = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.pk)

food_section/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse,reverse_lazy
from django.contrib.auth import login, logout,authenticate
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required
from food_section.models import food_section
from dishes.models import dishes
from outlet.models import outlet
# Create your views here.

@login_required(login_url = '/accounts/user_login')
def food_section_master(request,pk):
    user = request.user
    location = outlet.objects.all().filter(is_active=True)
    outlet_objects = outlet.objects.get(pk=pk)
    # location = outlet.objects.all()
    all_section = food_section.objects.all().filter(outlet_id=outlet_objects)
    outlet_object = outlet.objects.all().filter(is_active=True)
    item_count = {}
    for one in all_section:
        if dishes.objects.filter(food_section_id=one).exists():
            item_count[one.pk] = dishes.objects.filter(food_section_id=one).count()
        else:
            item_count[one.pk] = 0
    food_objects = all_section.first()
    data = {'all_section':all_section,'food_objects':food_objects,'item_count':item_count,'outlet_objects':outlet_objects,'location':location}
    return render(request, 'food_section/add_section.html',data)


@login_required(login_url = '/accounts/user_login')
def food_add(request,pk):
    user= request.user
    outlet_objects = outlet.objects.get(pk=pk)
    all_section=food_section.objects.all()
    food_objects = all_section.first()
    outlet_object = outlet.objects.all().filter(is_active=True)
    if request.method == "POST":
        section_name = request.POST['section_name']
        outlet_id = outlet.objects.get(pk=request.POST['outlet_id'])

        if food_section.objects.filter(section_name=section_name,outlet_id=outlet_objects).exists():
            error_msg='Food Section Name Already Exist!'
            data={'error_msg':error_msg,'food_objects':food_objects,'all_section':all_section,'outlet_object':outlet_object}
            return render(request,'food_section/add_section.html',data)
        else :
            food_section.objects.create(section_name=section_name,
                                        outlet_id=outlet_id)
            return HttpResponseRedirect(reverse('food_section:food_section_master',kwargs={'pk':outlet_objects.pk}))
    else:
        data={'food_objects':food_objects,'all_section':all_section,'outlet_object':outlet_object}
        return render (request,'food_section/add_section.html',data)


@login_required(login_url = '/accounts/user_login')
def food__section_update(request,pk,pk1):
    user= request.user
    outlet_objects = outlet.objects.get(pk=pk)
    food_obj = food_section.objects.get(pk=pk1)
    location = outlet.objects.all().filter(is_active=True)
    all_section=food_section.objects.all()
    food_objects = all_section.first()
    if request.method == "POST":
        section_name = request.POST['section_name']
        is_active = request.POST['is_active']
        if food_section.objects.filter(section_name=section_name,outlet_id=outlet_objects).exclude(section_name=food_obj.section_name).exists():
            error_msg='Food Section Name Already Exist!'
            data={'error_msg':error_msg,'food_objects':food_objects,'all_section':all_section,'location':location,'outlet_objects':outlet_objects}
            return render(request,'food_section/add_section.html',data)
        else:
            food_obj.section_name = section_name
            food_obj.is_active = is_active
            food_obj.save()
            return HttpResponseRedirect(reverse('food_section:food_section_master',kwargs={'pk':outlet_objects.pk}))

templates/food_section/add_section.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% load menu_item_count %}

{% block stylesheets %}
{% endblock stylesheets %}

{% block headscript %}
{% endblock headscript %}

{% block content %}
<div class="main">

    <div class="container mt-4">
    <form action="{% url 'food_section:food_add' outlet_objects.pk %}" method="POST">
    {% csrf_token %}
        <div class="row">
            <div class="col-3">
                <input type="text" name="section_name" id="section_name" class="form-control form-control-sm radius" placeholder="Add New Food Section" required>
            </div>
            <div class="col-3">
                <select name="outlet_id" id="outlet_id" class="form-control form-control-sm radius">
                    {% for one in location %}
                    <option value="{{one.pk}}">{{one.outlet_name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col">
                <button type="submit" class="btn btn-sm btn-warning radius">Add Section </button>
            </div>
            <div class="col">
                <a href="{% url 'dishes:all_dishes' outlet_objects.pk food_objects.pk %}" class="btn btn-sm btn-info radius" style="float:right;"><i class="fa fa-angle-left" aria-hidden="true"></i> </a>
            </div>
        </div>
    </form>
    </div>
    {% if error_msg %}<p style="color:red">{{error_msg}}</p>{% endif %}
    <div class="container mt-4">
        <div class="row">
            <div class="col">
                <div>
                    <table id="table_id" class="display table-bordered table-sm" style="width: 100%;;font-size: 12px">
                        <thead>
                            <tr>
                                <th>Sr. No.</th>
                                <th>Food Section Name</th>
                                 <th>Menu Item Count</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for one in all_section %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{one.section_name}}</td>
                                <td>{{item_count|get_item:one.pk}}</td>
                                {% if one.is_active == True %}
                                <td style="color:#50ef55">Active</td>
                                {% else %}
                                <td class="softer-text" style="color:#828586">Inactive</td>
                                {% endif %}
                                <td> <i class="fa fa-pencil" data-toggle="modal" data-target="#update{{one.pk}}"></i> </td>

                                <!-- Modal -->
                                <div class="modal fade" id="update{{one.pk}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Update Food Section</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <form action="{% url 'food_section:food__section_update' outlet_objects.pk one.pk  %}" method="POST">
                                                    {% csrf_token %}
                                                    <div class="form-group">
                                                        <label for="exampleInputEmail1">Food Section Name :</label>
                                                        <input type="text" class="form-control form-control-sm" id="section_name" name="section_name" value="{{one.section_name}}">
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="exampleInputEmail1">Status :</label>
                                                        <select name="is_active" id="is_active" class="form-control form-control-sm" >
                                                            <option value="True" {% if one.is_active == True %} selected {% endif %}>Active</option>
                                                            <option value="False" {% if one.is_active == False %} selected {% endif %}>Inactive</option>
                                                        </select>
                                                    </div>
                                                    <button type="submit" class="btn btn-primary">Update</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </tr>
                            {% endfor %}

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function() {
        $('#table_id').DataTable();
    });

</script>
{% endblock %}

{% block extrascript %}
{% endblock %}