chopstick/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('',views.home,name="home"),
    path('dishes/', include('dishes.urls')),
    path('food_section/', include('food_section.urls')),
    path('customer/', include('customer.urls')),
    path('orders/', include('orders.urls')),
    path('outlet/', include('outlet.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import include, path
from customer.views import *

app_name = 'customer'

urlpatterns = [
path('customer_master',customer_master,name='customer_master'),

# path('add_new_customer',add_new_customer,name='add_new_customer'),

path('update_customer/<int:pk>/<int:pk1>',update_customer,name='update_customer'),

path('customer_detail/<int:pk>/<int:pk1>',customer_detail,name='customer_detail'),

path('delete_order/<int:pk>/<int:pk1>',delete_order,name='delete_order'),

]

dishes/urls.py
from django.urls import include, path
from dishes.views import *

app_name = 'dishes'

urlpatterns = [
path('all_dishes/<int:pk>/<int:pk1>',all_dishes,name='all_dishes'),

path('menu/<int:pk>',menu,name='menu'),

path('add_dishes/<int:pk>/<int:pk1>',add_dishes,name='add_dishes'),

path('update_dish/<int:pk>/<int:pk1>/<int:pk2>',update_dish,name='update_dish'),

path('delete_dish/<int:pk>/<int:pk1>/<int:pk2>',delete_dish,name='delete_dish'),

]

customer/models.py
from django.db import models
from accounts.models import custom_user
from outlet.models import outlet
# Create your models here.

class customer(models.Model):
    custom_user_id = models.ForeignKey(custom_user,on_delete=models.CASCADE)
    # outlet_id = models.ForeignKey(outlet, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.pk)

orders/models.py
from django.db import models

from customer.models import customer
from extra_item.models import extra_item
from dishes.models import dishes
from outlet.models import outlet
# Create your models here.

class order(models.Model):
    order_id = models.CharField(max_length=50)
    customer_id  = models.ForeignKey(customer,on_delete=models.CASCADE)
    outlet_id = models.ForeignKey(outlet, on_delete=models.CASCADE)
    ONLINE = 1
    CASH =2
    PAYMENT_TYPE_CHOICES = (
      (ONLINE,'ONLINE'),
      (CASH,'CASH'),
    )
    payment_type  = models.PositiveIntegerField(choices=PAYMENT_TYPE_CHOICES)
    order_delivery_address = models.CharField(max_length=500)
    landmark = models.CharField(max_length=500,default="NA")
    total_bill  = models.IntegerField()

    PENDING= 1
    CANCLE = 2
    COMPLETE = 3
    DELIVERY = 4
    ORDER_STATUS_CHOICES = (
      (PENDING,'PENDING'),
      (CANCLE,'CANCLE'),
      (COMPLETE,'COMPLETE'),
      (DELIVERY,'DELIVERY'),
    )
    order_status = models.PositiveIntegerField(choices=ORDER_STATUS_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.pk)


class customer_order_detail(models.Model):
    order_id   = models.ForeignKey(order,on_delete=models.CASCADE)
    dish_id  = models.ForeignKey(dishes,on_delete=models.CASCADE)
    quantity   = models.IntegerField()
    amount    = models.IntegerField()
    extra_item_1 = models.BooleanField(default=False)
    extra_item_2 = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.pk)

customer/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse,reverse_lazy
from django.contrib.auth import login, logout,authenticate
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required

from customer.models import customer
from accounts.models import custom_user
from orders.models import order,customer_order_detail
from dishes.models import dishes
from food_section.models import food_section
from outlet.models import outlet
import math
# Create your views here.

@login_required(login_url = '/accounts/user_login')
def customer_master(request):
    user = request.user
    # outlet_objects = outlet.objects.get(pk=pk)
    all_customer = customer.objects.all()
    all_user= customer.objects.all().count()
    location = outlet.objects.all().filter(is_active=True)
    total_billing = {}
    last_order = {}
    for one in all_customer :
        sum = 0
        if order.objects.filter(customer_id=one).exists():
            last_order[one.pk] = order.objects.filter(customer_id=one).latest('created_at').created_at
            order_object = order.objects.filter(customer_id=one)

            for two in order_object:
                sum = sum + two.total_bill
                total_billing[one.pk]=sum
        else:
            total_billing[one.pk] = 'NO ORDERS'
            last_order [one.pk] = 'NO ORDERS'
    food_objects = food_section.objects.all().first()
    if request.method == "POST":
        last_date = request.POST['last_date']
        last_orders = order.objects.filter(created_at__date=last_date)
        for one in all_customer :
            sum = 0
            if order.objects.filter(customer_id=one,created_at__date=last_date).exists():
                last_order[one.pk] = order.objects.filter(customer_id=one,created_at__date=last_date).latest('created_at').created_at
                order_object = order.objects.filter(customer_id=one)

                for two in order_object:
                    sum = sum + two.total_bill
                    total_billing[one.pk]=sum
            else:
                total_billing[one.pk] = 'NO ORDERS'
                last_order [one.pk] = 'NO ORDERS'
        data = {'all_customer':all_customer,'all_user':all_user,'total_billing':total_billing,'last_order':last_order,'food_objects':food_objects,'last_date':last_date,'location':location}
        return render(request, 'customer/customer.html',data)
    else:
        data = {'all_customer':all_customer,'all_user':all_user,'total_billing':total_billing,'last_order':last_order,'food_objects':food_objects,'location':location}
        return render(request, 'customer/customer.html',data)

@login_required(login_url = '/accounts/user_login')
def update_customer(request,pk,pk1):
    user = request.user
    outlet_objects = outlet.objects.get(pk=pk)
    all_customer = customer.objects.get(pk=pk1)
    location = outlet.objects.all().filter(is_active=True)
    if request.method == "POST":
        full_name= request.POST['full_name']
        mobile_no= request.POST['mobile_no']
        email=request.POST['email']
        address= request.POST['address']
        all_customer.full_name=full_name
        all_customer.mobile_no=mobile_no
        all_customer.email=email
        all_customer.address=address
        all_customer.save()
        return HttpResponseRedirect(reverse('customer:customer_detail',kwargs={'pk':outlet_objects.pk,'pk1':all_customer.pk}))

# email = custom_user.objects.get(pk=request.POST['email'])

@login_required(login_url = '/accounts/user_login')
def customer_detail(request,pk,pk1):
    user= request.user
    outlet_objects = outlet.objects.get(pk=pk)
    all_customer = customer.objects.get(pk=pk1)
    order_details = order.objects.filter(customer_id=all_customer,outlet_id=outlet_objects)
    total_order_count=order_details.filter(outlet_id=outlet_objects).count()
    total_order_cancle=order_details.filter(order_status=2,outlet_id=outlet_objects).count()
    latest_order = order_details.all()
    customer_details = customer_order_detail.objects.filter(order_id=latest_order)
    location = outlet.objects.all().filter(is_active=True)
    error_msg = 'NO Order'
    error_massage = 'NO Order'

    sum = 0
    for one in order_details :
        sum = sum + one.total_bill
    food_objects = food_section.objects.all().filter(outlet_id=outlet_objects).first()
    data = {'all_customer':all_customer,'order_details':order_details,'total_order_count':total_order_count,
            'total_order_cancle':total_order_cancle,'sum':sum,'error_msg':error_msg,'latest_order':latest_order,
            'customer_details':customer_details,'food_objects':food_objects,'location':location,'outlet_objects':outlet_objects}
    return render (request,'customer/customer_detail.html',data)



@login_required(login_url = '/accounts/user_login')
def delete_order(request,pk,pk1):
    outlet_objects = outlet.objects.get(pk=pk)
    order_object = customer_order_detail.objects.get(pk=pk1)
    order_object.delete()
    return HttpResponseRedirect(reverse('customer:customer_master',kwargs={'pk':outlet_objects.pk}))

templates/customer/customer.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% load total_billing %}

{% block stylesheets %}
{% endblock stylesheets %}

{% block headscript %}
{% endblock headscript %}


{% block content %}
            <div class="main">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <input type="text" name="" id="" class="form-control form-control-sm radius" placeholder="Enter Name , Mobile Or Item ">
                        </div>
                        <div class="col">
                            <button class="btn btn-sm search-btn radius">SEARCH</button>
                        </div>

                    </div>
                </div>

                <div class="container mt-4">
                    <div class="row">
                        <div class="col-2">
                            <a href="#" class="tabs active-tab all-customer">ALL CUSTOMERS</a>
                        </div>
                        <div class="col-2">
                            <a href="#" class="tabs green add-customer">UPLOAD EXCEL</a>
                        </div>
                        <div class="col-2">
                            <a href="#" class="tabs red bold add-customer"><span class="gray">TOTAL CUSTOMER :</span> <span style="font-size:18px">{{all_user}}</span></a>
                        </div>
                        <div class="col-4">

                        </div>
                        <div class="col-2">
                            <button class="btn btn-sm green-btn notify-btn" data-toggle="modal" data-target="#notify">SEND NOTIFICATION</button>

                            <div class="modal fade" id="notify" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">SEND NOTIFICATION</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <form>
                                                <div class="form-group">
                                                    <select class="form-control form-control-sm radius">
                                                        <option disabled selected style="display: none">Select Subject</option>
                                                        <option>Order Ready</option>
                                                    </select>
                                                </div>
                                                <div class="form-group">
                                                    <textarea class="form-control form-control-sm radius" placeholder="Message"></textarea>
                                                </div>
                                                <div class="form-row">
                                                    <div class="col">
                                                        <select class="form-control form-control-sm radius">
                                                            <option disabled selected style="display: none">Send Via</option>
                                                            <option>SMS</option>
                                                            <option>EMAIL</option>
                                                        </select>
                                                    </div>
                                                    <div class="col">
                                                        <button class="btn btn-sm green-btn radius">SEND</button>
                                                    </div>
                                                </div>

                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

                <div class="container mt-4">
                    <div class="row">
                        <div class="col-2">
                            <label>Last Ordered on:</label>
                        </div>
                        <div class="col-6">
                            <form method="POST" action="#">
                            {% csrf_token %}
                                <div class="row">
                                    <div class="col">
                                        <input type="date" name="last_date" value="{{last_date}}" class="form-control form-control-sm" required>
                                    </div>
                                    <div class="col">
                                        <button class="btn btn-sm green-btn notify-btn">SEARCH</button>
                                    </div>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>

                <div class="container mt-4">
                    <div class="row">
                        <div class="col">
                            <div>
                                <table id="table_id" class="display table-bordered table-sm" style="width: 100%;;font-size: 12px">
                                    <thead>
                                        <tr>
                                            <th>Sr. No.</th>
                                            <th>Select</th>
                                            <th>OTP</th>
                                            <th>Customer Name</th>
                                            <th>Customer Mobile</th>
                                            <th>Customer Address</th>
                                            <th>Total Billing</th>
                                            <th>Last Ordered on</th>
                                            <!--<th>Action</th>-->
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for one in all_customer %}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td><input type="checkbox" name="" id=""></td>
                                            <td>{{one.custom_user_id.otp}}</td>
                                            <td><a href="{% url 'customer:customer_detail' outlet_objects.pk one.pk %}">{{one.full_name}}</a></td>
                                            <td>{{ one.custom_user_id.mobile_no }}</td>
                                            <td>{{one.address}}</td>
                                            <td><i class="fa fa-inr red" aria-hidden="true"></i><span class="red"> {{total_billing|get_item:one.pk}} </span></td>
                                            <td>{{last_order|get_item:one.pk}}</td>
                                        </tr>
                                        {% endfor %}

                                    </tbody>
                                </table>


                            </div>
                        </div>
                    </div>
                </div>

            </div>
{% endblock %}

{% block script %}
<script>
        $(document).ready(function() {
            $('#table_id').DataTable( {

            buttons: [
                'excelHtml5',
            ],
    });
});

</script>

{% endblock %}

{% block extrascript %}
    <script>
        $('#order-check1').click(function() {
            if ($('#order-div1').css('display') == 'none') {
                $('#order-div1').show();
            } else {
                $('#order-div1').hide();
            }
        });

        $('#order-check2').click(function() {
            if ($('#order-div2').css('display') == 'none') {
                $('#order-div2').show();
            } else {
                $('#order-div2').hide();
            }
        });
    </script>
{% endblock %}

templates/customer/customer_detail.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block stylesheets %}
{% endblock stylesheets %}

{% block headscript %}
{% endblock headscript %}


{% block content %}
<div class="main">
    <div class="container mt-3">
        <div class="row">
            <div class="col-6" style="border-right: 1px solid #d9d9d9">
                <div class="left-side-div">
                <form action="{% url 'customer:update_customer' outlet_objects.pk all_customer.pk %}" method="POST">
                {% csrf_token %}
                    <h6 class="title-heading red big">CUSTOMER DETAILS
                        <span style="float: right;color:black"> <button type="submit" class="btn btn-sm "><i class="fa fa-floppy-o" aria-hidden="true"></i></button></span>
                    </h6>
                    <div class="menu-items-div">
                        <div class="row">
                            <div class="col-5">
                                <div class="cust-detail">
                                    <h6 style="margin-top:3px">Full Name :</h6>
                                    <h6 style="margin-top:12px">Mobile Number :</h6>
                                    <h6 style="margin-top:12px">Email ID :</h6>
                                    <h6 style="margin-top:12px"> Address :</h6>
                                </div>
                            </div>
                            <div class="col">
                                <div class="cust-detail-right">
                                    <h6><input type="text" class="form-control form-control-sm radius" style="height:20px;" name="full_name" value="{{all_customer.full_name}}"></h6>
                                    <h6><input type="text" class="form-control form-control-sm radius" style="height:20px;" name="mobile_no" value="{{all_customer.custom_user_id.mobile_no}}"></h6>
                                    <h6><input type="text" class="form-control form-control-sm radius" style="height:20px;" name="email" value="{{all_customer.custom_user_id.email}}"></h6>
                                    <h6><input type="text" class="form-control form-control-sm radius" style="height:20px;" name="address" value="{{all_customer.address}}"></h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                    {% if order_details %}
                    <div class="menu-items-div mt-3" style="height:430px;">
                        <div class="row text-center">
                            <div class="col">
                                <h6 class="cust-label gray">TOTAL ORDERS</h6>
                                <h6 class="cust-label-dw red bold">{{total_order_count}}</h6>
                            </div>
                            <div class="col">
                                <h6 class="cust-label gray">TOTAL CANCELS</h6>
                                <h6 class="cust-label-dw red bold">{{total_order_cancle}}</h6>
                            </div>
                            <div class="col">
                                <h6 class="cust-label gray">TOTAL SALES</h6>
                                <h6 class="cust-label-dw red bold"><i class="fa fa-inr red" aria-hidden="true"></i>{{sum}}</h6>
                            </div>
                        </div>
                        <div style="overflow-y:scroll;overflow-x:hidden;">
                            {% for order in order_details %}
                            <div class="total-menu-item-div">
                                <div class="menu-item-div" style="width:81%;margin: 0 auto;">
                                    <div class="row">
                                        <div class="col-9">
                                            <h6 class="item-name">Order Date: <span class="red bold">{{ order.created_at|date:"d M Y" }}</span></h6>
                                        </div>
                                        <div class="col-3">
                                            <span class="item-price red bold"><i class="fa fa-inr red" aria-hidden="true"></i> {{order.total_bill}} </span>&nbsp;&nbsp; <span> <i class="fa fa-angle-right" id="order-check1{{order.pk}}"></i></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        {% else %}
                        <center>
                            <p style="color:#ff0000 ;margin-top:50px">NO ORDERS PLACED YET</p>
                        </center>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% if order_details %}
            <div class="col-6">
                
                
            <div class="right-side-div">
                <h6 class="title-heading red big">ORDER DETAILS<a href="{% url 'customer:customer_master' outlet_objects.pk %}" class="btn btn-sm btn-info" style="float:right;margin-left:5px;"><i class="fa fa-angle-left" aria-hidden="true"></i></a> <a href="#" class="btn btn-sm btn-warning radius" style="float:right;">PRINT</a></h6>
                <span class="title-heading red">DELIVERY DETAILS</span>
                {% for order in order_details %}
                    <div id="order-div{{order.pk}}" style="display:none">
                        <div class="row">
                            <div class="col-5">
                                <div class="cust-detail">
                                    <h6>Full Name :</h6>
                                    <h6>Mobile Number :</h6>
                                    <h6>Delivery Address :</h6>
                                </div>
                            </div>
                            <div class="col">
                                <div class="cust-detail-right">
                                    <h6>{{order.customer_id.full_name}}</h6>
                                    <h6>{{order.customer_id.custom_user_id.mobile_no}}</h6>
                                    <h6>{{order.order_delivery_address}}</h6>
                                </div>
                            </div>
                        </div>
                        <div style="overflow-y:scroll;overflow-x:hidden;">
                            <div class="menu-items-div mt-2" style="height:380px" >
                                <div class="total-menu-item-div" >
                                {% for one in order.customer_order_detail_set.all %}
                                    <div class="menu-item-div">
                                        <div class="row">
                                            <div class="col-8">
                                                <h6 class="item-name"><i class="fa fa-square {% if one.dish_id.dish_type == 2 %} nv{% else %}green{% endif %}"></i> {{one.dish_id.dish_name}}</h6>
                                            </div>
                                            <div class="col-4">
                                                <span class="item-price red bold"><i class="fa fa-inr red" aria-hidden="true"></i> {{one.amount}} </span>&nbsp;&nbsp; <span><a href="#"><i class="fa fa-trash red" data-toggle="modal" data-target="#delete{{one.pk}}"></i></a></span>
                                                <div class="modal fade" id="delete{{one.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                    <div class="modal-dialog">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h5 class="modal-title" id="exampleModalLabel">Delete Order</h5>
                                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                    <span aria-hidden="true">&times;</span>
                                                                </button>
                                                            </div>
                                                            <div class="modal-body">
                                                                <p>Are you sure want to delete?</p><br>
                                                                <a href="{% url 'customer:delete_order' outlet_objects.pk one.pk %}" class="btn btn-danger">Delete</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="menu-qty-div">
                                        <div class="row">
                                            <div class="col">
                                                <div class="quat-div">
                                                    <span style="font-size: 14px">Qty</span>
                                                    <select name="quantity" id="quantity" class="quantity" readonly>
                                                        <option value="{{one.pk}}">{{one.quantity}}</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-7">
                                                <div>
                                                    <div class="form-check form-check-inline">
                                                        <input class="form-check-input" type="checkbox" id="extra_item_1" value="True" {% if one.extra_item_1 == True%} checked {% endif %}>
                                                        <label class="form-check-label" for="extra1">Extra Item</label>
                                                    </div>
                                                    <div class="form-check form-check-inline">
                                                        <input class="form-check-input" type="checkbox" id="extra_item_2" value="True" {% if one.extra_item_2 == True%} checked {% endif %}>
                                                        <label class="form-check-label" for="extra2">Extra Item</label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        

                        <div class="mt-3">
                            <div class="row">
                                <div class="col-5">
                                    <div class="cust-detail">
                                        <h6>Payment Method:</h6>
                                        <h6>Payment Status:</h6>
                                        <h6>Order Total Amount:</h6>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="cust-detail-right">
                                        {% if order.payment_type == 1 %}
                                        <h6>ONLINE</h6>
                                        {% else %}
                                        <h6>CASH</h6>
                                        {% endif %}
                                        {% if order.order_status == 1 %}
                                        <h6>Pending</h6>
                                        {% elif order.order_status == 2 %}
                                        <h6>CANCLE</h6>
                                        {% elif order.order_status == 3 %}
                                        <h6>COMPLETE</h6>
                                        {% elif order.order_status == 4 %}
                                        <h6>DELIVERY</h6>
                                        {% endif %}
                                        <h6><i class="fa fa-inr red" aria-hidden="true"></i> {{order.total_bill}}</h6>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

{% block script %}
<script>
    $(document).ready(function() {
        $('#table_id').DataTable();
    });

</script>
{% endblock %}

{% block extrascript %}
<script>
    {% for order in order_details %}
    $('#order-check1{{order.pk}}').click(function() {
        if ($('#order-div{{order.pk}}').css('display') == 'none') {
            $('#order-div{{order.pk}}').show();
        } else {
            $('#order-div{{order.pk}}').hide();
        }
    }); 
    
    {% endfor %}

</script>

<script>

$(".showDesc").click(function() {
  var $target = $(this).closest('.feedContainer').next(".descContainer").toggleClass("show");
  $(".descContainer").not($target).removeClass('show'); // hide other open elements
});
</script>

{% endblock %}