chopstick/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('',views.home,name="home"),
    path('dishes/', include('dishes.urls')),
    path('food_section/', include('food_section.urls')),
    path('customer/', include('customer.urls')),
    path('orders/', include('orders.urls')),
    path('outlet/', include('outlet.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dishes/urls.py
from django.urls import include, path
from dishes.views import *

app_name = 'dishes'

urlpatterns = [
path('all_dishes/<int:pk>/<int:pk1>',all_dishes,name='all_dishes'),

path('menu/<int:pk>',menu,name='menu'),

path('add_dishes/<int:pk>/<int:pk1>',add_dishes,name='add_dishes'),

path('update_dish/<int:pk>/<int:pk1>/<int:pk2>',update_dish,name='update_dish'),

path('delete_dish/<int:pk>/<int:pk1>/<int:pk2>',delete_dish,name='delete_dish'),

]

orders/urls.py
from django.urls import include, path
from orders.views import *

app_name = 'orders'

urlpatterns = [

path('select_order_item/<int:pk>',select_order_item,name='select_order_item'),

path('order_placed/<int:pk>',order_placed,name='order_placed'),

path('success_order/<int:pk>',success_order,name='success_order'),


path('order_master/<int:pk>',order_master,name='order_master'),

path('cust_order_details',cust_order_details,name='cust_order_details'),

path('order_cancle/<int:pk>',order_cancle,name='order_cancle'),

path('today_order/<int:pk>',today_order,name='today_order'),

path('update_status/<int:pk>/<int:pk1>',update_status,name='update_status'),

path('new_order/<int:pk>',new_order,name='new_order'),

path('order_details/<int:pk>/<int:pk1>',order_details,name='order_details'),

path('get_customer_detail',get_customer_detail,name='get_customer_detail'),

path('existing_order_update/<int:pk>/<int:pk1>',existing_order_update,name='existing_order_update'),

path('add_new_items_existing_order/<int:pk>/<int:pk1>',add_new_items_existing_order,name='add_new_items_existing_order'),

path('add_new_order_submit/<int:pk>',add_new_order_submit,name='add_new_order_submit'),

path('delete_one_item_from_order/<int:pk>/<int:pk1>',delete_one_item_from_order,name='delete_one_item_from_order'),
]

orders/models.py
from django.db import models

from customer.models import customer
from extra_item.models import extra_item
from dishes.models import dishes
from outlet.models import outlet
# Create your models here.

class order(models.Model):
    order_id = models.CharField(max_length=50)
    customer_id  = models.ForeignKey(customer,on_delete=models.CASCADE)
    outlet_id = models.ForeignKey(outlet, on_delete=models.CASCADE)
    ONLINE = 1
    CASH =2
    PAYMENT_TYPE_CHOICES = (
      (ONLINE,'ONLINE'),
      (CASH,'CASH'),
    )
    payment_type  = models.PositiveIntegerField(choices=PAYMENT_TYPE_CHOICES)
    order_delivery_address = models.CharField(max_length=500)
    landmark = models.CharField(max_length=500,default="NA")
    total_bill  = models.IntegerField()

    PENDING= 1
    CANCLE = 2
    COMPLETE = 3
    DELIVERY = 4
    ORDER_STATUS_CHOICES = (
      (PENDING,'PENDING'),
      (CANCLE,'CANCLE'),
      (COMPLETE,'COMPLETE'),
      (DELIVERY,'DELIVERY'),
    )
    order_status = models.PositiveIntegerField(choices=ORDER_STATUS_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.pk)


class customer_order_detail(models.Model):
    order_id   = models.ForeignKey(order,on_delete=models.CASCADE)
    dish_id  = models.ForeignKey(dishes,on_delete=models.CASCADE)
    quantity   = models.IntegerField()
    amount    = models.IntegerField()
    extra_item_1 = models.BooleanField(default=False)
    extra_item_2 = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.pk)

orders/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse,reverse_lazy
from django.contrib.auth import login, logout,authenticate
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required
from datetime import date, timedelta,datetime
from django.http import JsonResponse

from orders.models import order,customer_order_detail
from customer.models import customer
from accounts.models import custom_user
from food_section.models import food_section
from dishes.models import dishes
from outlet.models import outlet
from django.utils.datastructures import MultiValueDictKeyError
import random
# Create your views here.

def select_order_item(request,pk):
    outlet_objects = outlet.objects.get(pk=pk)
    all_dishes =  dishes.objects.filter(is_active=True,food_section_id__outlet_id=outlet_objects).all()
    if request.method == "POST":
        selected_dish = []
        not_selected = []
        for one_dish in all_dishes:
            try:
                dish = dishes.objects.get(pk=request.POST['dish'+ str(one_dish.pk)])
            except MultiValueDictKeyError:
                dish = " "

            quantity = request.POST['quantity' + str(one_dish.pk)]

            try:
                extra_item1 = request.POST['extra_item1' + str(one_dish.pk)]
            except MultiValueDictKeyError:
                extra_item1 = "0"

            try:
                extra_item2 = request.POST['extra_item2' + str(one_dish.pk)]
            except MultiValueDictKeyError:
                extra_item2 = "0"

            if dish != " ":
                selected_dish.append([dish,quantity,extra_item1,extra_item2])
            else:
                not_selected.append([dish,quantity,extra_item1,extra_item2])
        total_amount = 0
        total_quantity = 0
        for item in selected_dish:
            total_quantity = total_quantity + int(item[1])

            if item[2] == "1":
                extra_item1_cost = item[0].extra_item_cost_1
            else:
                extra_item1_cost = 0

            if item[3] == "1":
                extra_item2_cost = item[0].extra_item_cost_2
            else:
                extra_item2_cost = 0

            total_amount = total_amount + (int(item[0].amount) * int(item[1])) + int(extra_item1_cost) + int(extra_item2_cost)

        data = {'selected_dish':selected_dish,'total_quantity':total_quantity,'total_amount':total_amount,'outlet_objects':outlet_objects}
        return render(request,'orders/order_cart.html',data)



def order_placed(request,pk):
    outlet_objects = outlet.objects.get(pk=pk)
    all_dishes =  dishes.objects.filter(is_active=True).all()
    if request.method == "POST":
        selected_dish = []
        not_selected = []
        for one_dish in all_dishes:
            try:
                dish = dishes.objects.get(pk=request.POST['dish'+ str(one_dish.pk)])
            except MultiValueDictKeyError:
                dish = "0"

            try:
                quantity = request.POST['quantity' + str(one_dish.pk)]
                if quantity != "0":
                    quantity = quantity
                else:
                    quantity = "0"
            except MultiValueDictKeyError:
                quantity = "0"

            try:
                extra_item1 = request.POST['extra_item1' + str(one_dish.pk)]
            except MultiValueDictKeyError:
                extra_item1 = "0"

            try:
                extra_item2 = request.POST['extra_item2' + str(one_dish.pk)]
            except MultiValueDictKeyError:
                extra_item2 = "0"

            if dish != "0":
                selected_dish.append([dish,quantity,extra_item1,extra_item2])
            else:
                not_selected.append([dish,quantity,extra_item1,extra_item2])

        user_name = request.POST['user_name']
        user_mobile = request.POST['user_mobile']
        user_address = request.POST['user_address']
        landmark = request.POST['landmark']
        payment = request.POST['payment']
        if payment == "1":
            pay = 1
        else:
            pay = 2
        if custom_user.objects.filter(username =user_mobile).exists():
            customuser_obj = custom_user.objects.get(username =user_mobile)
            customer_obj = customer.objects.get(custom_user_id=customuser_obj)
            number = random.randint(1000, 9999)
            customuser_obj.otp = number
            customuser_obj.save()
        else:
            number = random.randint(1000, 9999)
            customuser_obj = custom_user.objects.create(username=user_mobile,
                                                        mobile_no=user_mobile,
                                                        password=make_password(user_mobile),
                                                        user_role=3,
                                                        otp=number)
            customer_obj = customer.objects.create(custom_user_id=customuser_obj,
                                                full_name=user_name,
                                                address=user_address)
        total_amount = 0
        for item in selected_dish:
            if item[2] == "1":
                extra_item1_cost = item[0].extra_item_cost_1
            else:
                extra_item1_cost = 0

            if item[3] == "1":
                extra_item2_cost = item[0].extra_item_cost_2
            else:
                extra_item2_cost = 0

            total_amount = total_amount + (int(item[0].amount) * int(item[1])) + int(extra_item1_cost) + int(extra_item2_cost)

        todays_date = date.today()
        order_id = str(customuser_obj.username[:4]) + "/" + str(todays_date.day) + "" + str(todays_date.month) + "/" + str(todays_date.year)
        order_obj = order.objects.create(order_id=order_id,
                                        outlet_id = outlet_objects,
                                        customer_id=customer_obj,
                                        payment_type=pay,
                                        order_delivery_address=user_address,
                                        landmark=landmark,
                                        total_bill=total_amount,
                                        order_status=1)
        for one_selected in selected_dish:
            if one_selected[2] == "1":
                extra_item_1 = True
                cost_extra1 = one_selected[0].extra_item_cost_1
            else:
                extra_item_1 = False
                cost_extra1 = 0

            if one_selected[3] == "1":
                extra_item_2 = True
                cost_extra2 = one_selected[0].extra_item_cost_2
            else:
                extra_item_2 = False
                cost_extra2 = 0
            one_amount = int(one_selected[1]) * int(one_selected[0].amount) + int(cost_extra1) + int(cost_extra2)
            customer_order_detail.objects.create(order_id=order_obj,
                                                dish_id=one_selected[0],
                                                quantity=one_selected[1],
                                                amount=one_amount,
                                                extra_item_1=extra_item_1,
                                                extra_item_2=extra_item_2)
        return HttpResponseRedirect(reverse('orders:success_order',kwargs={'pk':outlet_objects.pk}))


def success_order(request,pk):
    outlet_objects = outlet.objects.get(pk=pk)
    data = {'outlet_objects':outlet_objects}
    return render(request,'orders/order_success.html',data)


@login_required(login_url = '/accounts/web_login')
def cust_order_details(request):
    user = request.user
    location = outlet.objects.all().filter(is_active=True)
    all_customer = customer.objects.get(custom_user_id=user)
    order_details = order.objects.filter(customer_id=all_customer).all()
    customer_details = customer_order_detail.objects.filter(order_id=order_details)
    data ={'all_customer':all_customer,'order_details':order_details,'customer_details':customer_details,'location':location}
    return render (request,'orders/cust_order_detail.html',data)

@login_required(login_url = '/accounts/user_login')
def order_master(request,pk):
    user= request.user
    location = outlet.objects.all().filter(is_active=True)
    outlet_objects = outlet.objects.get(pk=pk)
    all_orders = order.objects.all().exclude(order_status = 2).filter(outlet_id=outlet_objects)
    total_complete = order.objects.filter(order_status = 3).count()
    total_pending = order.objects.filter(order_status = 1).count()
    total_cancle = order.objects.filter(order_status = 2).count()
    item_count = {}
    sum = 0
    for one in all_orders:
        sum = sum + one.total_bill
        if customer_order_detail.objects.filter(order_id=one).exists():
            item_count[one.pk] = customer_order_detail.objects.filter(order_id=one).count()
        else:
            item_count[one.pk] = 0
    food_objects = food_section.objects.all().filter(outlet_id=outlet_objects).first()
    data = {'all_orders':all_orders,'total_complete':total_complete,'total_pending':total_pending,'total_cancle':total_cancle,
    'food_objects':food_objects,'item_count':item_count,'sum':sum,'outlet_objects':outlet_objects,'location':location}
    return render(request,'orders/orders.html',data)


@login_required(login_url = '/accounts/user_login')
def today_order(request,pk):
    user= request.user
    outlet_objects = outlet.objects.get(pk=pk)
    location = outlet.objects.all().filter(is_active=True)
    todays_date = date.today()
    all_orders = order.objects.filter(created_at__date=todays_date,outlet_id=outlet_objects).all()
    total_complete = order.objects.filter(order_status = 3,created_at__date=todays_date).count()

templates/orders/order_success.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Chopssticks-Success</title>
    <style>

    </style>
</head>

<body>
    <div class="">
        <section class="" style="height:100vh">
            <div class="login-web-box">
                    <div class="">
                        <div style="padding-top:110px">

                            <p class="index-pg-line">Your Order has been placed Successfully. </p>

                            <br>
                            <center>
                                <a href="{% url 'orders:cust_order_details' %}" class="btn btn-sm a" style="font-size: 12px;background-color:#01e55a;color: #fff;width: 40%">MY ORDERS</a>
                            </center>
                        </div>
                    </div>
            </div>
        </section>
    </div>

</body>

</html>

templates/orders/orders.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% load item_counts %}

{% block stylesheets %}
{% endblock stylesheets %}

{% block headscript %}
{% endblock headscript %}

{% block content %}
<div class="main">
    <div class="container">
        <div class="row">
            <div class="col">
                <input type="text" name="" id="" class="form-control form-control-sm radius" placeholder="Enter Name ,Mobile Or Item">
            </div>
            <div class="col">
                <button class="btn btn-sm search-btn radius">SEARCH</button>
            </div>

            <div class="col-2">
                <a href="{% url 'orders:new_order' outlet_objects.pk %}" target="_blank" class="btn btn-sm green-btn radius"><i class="fa fa-plus" aria-hidden="true"></i><b> NEW ORDER </b> </a>
            </div>

        </div>
    </div>

    <div class="container mt-4">
        <div class="row">
            <div class="col-5">
                <div class="tabs-div">
                    <a href="{% url 'orders:today_order' outlet_objects.pk %}" class="tabs inactive-tab">TODAY </a> &nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'orders:order_master' outlet_objects.pk %}" class="tabs  active-tab">ALL ORDERS </a> &nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'orders:order_cancle' outlet_objects.pk %}" class="tabs inactive-tab">CANCELLED ORDERS</a> &nbsp;&nbsp;&nbsp;&nbsp;
                </div>
            </div>
            <div class="col">

            </div>
            <div class="col">
                <div class="row">
                    <div class="col" style="margin: 0px;padding: 0px;">
                        <label for="today_date" class="date1">TOTAL PENDING<br>{{total_pending}}</label>
                    </div>
                    <div class="col" style="margin: 0px;padding: 0px;">
                        <label for="today_date" class="date1"> TOTAL COMPLETE<br>{{total_complete}} </label>
                    </div>
                    <div class="col" style="margin: 0px;padding: 0px;">
                        <label for="today_date" class="date1"> TOTAL CANCEL<br>{{total_cancle}} </label>
                    </div>
                    <div class="col" style="margin: 0px;padding: 0px;">
                        <label for="today_date" class="date2"> TOTAL SALES <br> <i class="fa fa-inr red" aria-hidden="true"></i> <span class="red">{{sum}}</span> </label>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="container ">
        <div class="row">
            <div class="col">
                <div>
                    <table id="table_id" class="display table-bordered table-sm" style="width: 100%;;font-size: 12px">
                        <thead>
                            <tr>
                                <th>Order Id</th>
                                <th>Customer Mobile</th>
                                <th>Order Time</th>
                                <th>Customer Name</th>
                                <th>Item</th>
                                <th>Total Bill</th>
                                <th>Payment</th>
                                <th>Orders Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for one in all_orders %}
                            <tr>
                                <td><a href="{% url 'orders:order_details' outlet_objects.pk  one.pk %}">{{one.order_id}}</a></td>
                                <td><input type="checkbox" id="" name=""> {{one.customer_id.custom_user_id.mobile_no}}</td>
                                <td>{{one.created_at}}</td>
                                <td>{{one.customer_id.full_name}}</td>
                                <td>{{item_count|get_item:one.pk}}</td>
                                <td><i class="fa fa-inr red" aria-hidden="true"></i><span class="red"> {{one.total_bill}}</span></td>
                                {% if one.payment_type == 1 %}
                                <td>ONLINE</td>
                                {% else %}
                                <td>CASH</td>
                                {% endif %}
                                <form action="{% url 'orders:update_status' outlet_objects.pk one.pk %}" method="POST">
                                {% csrf_token %}
                                <td>
                                    <select name="order_status" id="order_status" class=" {% if one.order_status == 1 %}orange {% elif one.order_status == 4 %} blue {% elif one.order_status == 2 %} red {% elif one.order_status == 3 %} green {%endif%}select-div">
                                        <option value="1" class="orange" {% if one.order_status == 1 %} selected {%endif%}><span>PENDING</span></option>
                                        <option value="4" class="blue" {% if one.order_status == 4 %} selected {%endif%}><span>DELIVERY</span></option>
                                        <option value="2" class="red" {% if one.order_status == 2 %} selected {%endif%}><span>CANCLE</span></option>
                                        <option value="3" class="green" {% if one.order_status == 3 %} selected {%endif%}><span>COMPLETE</span></option>
                                    </select>
                                </td>
                                <td><center><button type="submit" class="btn-primary "><i class="fa fa-save"></i></button></center></td>
                                </form>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
    {% endblock %}

    {% block script %}

    <script>
        $(document).ready(function() {
            $('#table_id').DataTable();
        });

    </script>
    {% endblock %}

    {% block extrascript %}
    <script>
        $(function() {
            $('#order-check1').click(function() {
                if ($(this).is(':checked')) {
                    $('#order-div1').show();
                } else {
                    $('#order-div1').hide();
                }
            });

            $('#order-check2').click(function() {
                if ($(this).is(':checked')) {
                    $('#order-div2').show();
                } else {
                    $('#order-div2').hide();
                }
            });

            $('#order-check3').click(function() {
                if ($(this).is(':checked')) {
                    $('#order-div3').show();
                } else {
                    $('#order-div3').hide();
                }
            });

            $('#order-check4').click(function() {
                if ($(this).is(':checked')) {
                    $('#order-div4').show();
                } else {
                    $('#order-div4').hide();
                }
            });
        });

    </script>
    <script>
        var d = new Date();
        var time = d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds();

        document.getElementById("demo").innerHTML = d.toDateString();
        document.getElementById("time").innerHTML = time;
    </script>

    {% endblock %}

templates/orders/todays_order.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% load item_counts %}


{% block stylesheets %}
{% endblock stylesheets %}

{% block headscript %}
{% endblock headscript %}

{% block content %}
<div class="main">
    <div class="container">
        <div class="row">
            <div class="col">
                <input type="text" name="" id="" class="form-control form-control-sm radius" placeholder="Enter Name ,Mobile Or Item">
            </div>
            <div class="col">
                <button class="btn btn-sm search-btn radius">SEARCH</button>
            </div>

            <div class="col-2">
                <a href="{% url 'orders:new_order' outlet_objects.pk %}" target="_blank" class="btn btn-sm green-btn radius"><b> <i class="fa fa-plus" aria-hidden="true"></i> NEW ORDER</b> </a>
            </div>

        </div>
    </div>

    <div class="container mt-4">
        <div class="row">
            <div class="col">
                <div class="tabs-div">
                    <a href="{% url 'orders:today_order' outlet_objects.pk %}" class="tabs active-tab">TODAY </a> &nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'orders:order_master' outlet_objects.pk %}" class="tabs  inactive-tab">ALL ORDERS </a> &nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'orders:order_cancle' outlet_objects.pk %}" class="tabs inactive-tab">CANCELLED ORDERS</a> &nbsp;&nbsp;&nbsp;&nbsp;
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-4">
        <div class="row">
            <div class="col">
                <label for="today_date" class="date"> Today's Date : <small class="date-div" id="demo"></small></label>
            </div>
            <div class="col">
                <label for="current_time" class="date">Current Time :<small class="date-div" id="time"></small> </label>
            </div>
            <div class="col">
                <div class="row">
                    <div class="col" style="margin: 0px;padding: 0px;">
                        <label for="today_date" class="date1">TOTAL PENDING<br>{{total_pending}}</label>
                    </div>
                    <div class="col" style="margin: 0px;padding: 0px;">
                        <label for="today_date" class="date1"> TOTAL COMPLETE<br>{{total_complete}} </label>
                    </div>
                    <div class="col" style="margin: 0px;padding: 0px;">
                        <label for="today_date" class="date1"> TOTAL CANCEL<br>{{total_cancle}} </label>
                    </div>
                    <div class="col" style="margin: 0px;padding: 0px;">
                        <label for="today_date" class="date2"> TOTAL <br>SALES <br> <i class="fa fa-inr red" aria-hidden="true"></i> <span class="red">{{sum}}</span> </label>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="container ">
        <div class="row">
            <div class="col">
                <div>
                    <table id="table_id" class="display table-bordered table-sm" style="width: 100%;;font-size: 12px">
                        <thead>
                            <tr>
                                <th>Order Id</th>
                                <th>Customer Mobile</th>
                                <th>Order Time</th>
                                <th>Customer Name</th>
                                <th>Item</th>
                                <th>Total Bill</th>
                                <th>Payment</th>
                                <th>Orders Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for one in all_orders %}
                            <tr>
                                <td><a href="{% url 'orders:order_details' outlet_objects.pk one.pk %}">{{one.order_id}}</a></td>
                                <td><input type="checkbox" id="" name=""> {{one.customer_id.custom_user_id.mobile_no}}</td>
                                <!--<td><input type="checkbox" id="" name=""></td>-->
                                <td>{{one.created_at|time:"h:i:s A"}}</td>
                                <td>{{one.customer_id.full_name}}</td>
                                <td>{{item_count|get_item:one.pk}}</td>
                                <td><i class="fa fa-inr red" aria-hidden="true"></i><span class="red"> {{one.total_bill}}</span></td>
                                {% if one.payment_type == 1 %}
                                <td>ONLINE</td>
                                {% else %}
                                <td>CASH</td>
                                {% endif %}
                                <form action="{% url 'orders:update_status' outlet_objects.pk  one.pk %}" method="POST">
                                {% csrf_token %}
                                <td>
                                    <select name="order_status" id="order_status" class=" {% if one.order_status == 1 %}orange {% elif one.order_status == 4 %} blue {% elif one.order_status == 2 %} red {% elif one.order_status == 3 %} green {%endif%}select-div">
                                        <option value="1" class="orange" {% if one.order_status == 1 %} selected {%endif%}><span>PENDING</span></option>
                                        <option value="4" class="blue" {% if one.order_status == 4 %} selected {%endif%}><span>DELIVERY</span></option>
                                        <option value="2" class="red" {% if one.order_status == 2 %} selected {%endif%}><span>CANCLE</span></option>
                                        <option value="3" class="green" {% if one.order_status == 3 %} selected {%endif%}><span>COMPLETE</span></option>
                                    </select>
                                </td>
                                <td><center><button type="submit" class="btn-primary"><i class="fa fa-save"></i></button></center></td>
                                </form>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
    {% endblock %}

    {% block script %}

    <script>
        $(document).ready(function() {
            $('#table_id').DataTable();
        });

    </script>
    {% endblock %}

    {% block extrascript %}
    <script>
        $(function() {
            $('#order-check1').click(function() {
                if ($(this).is(':checked')) {
                    $('#order-div1').show();
                } else {
                    $('#order-div1').hide();
                }
            });

            $('#order-check2').click(function() {
                if ($(this).is(':checked')) {
                    $('#order-div2').show();
                } else {
                    $('#order-div2').hide();
                }
            });

            $('#order-check3').click(function() {
                if ($(this).is(':checked')) {
                    $('#order-div3').show();
                } else {
                    $('#order-div3').hide();
                }
            });

            $('#order-check4').click(function() {
                if ($(this).is(':checked')) {
                    $('#order-div4').show();
                } else {
                    $('#order-div4').hide();
                }
            });
        });

    </script>
    <script>
        var d = new Date();
        var time = d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds();

        document.getElementById("demo").innerHTML = d.toDateString();
        document.getElementById("time").innerHTML = time;
    </script>

    {% endblock %}