accounts/urls.py
from django.urls import include, path
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
path('user_login',user_login,name='user_login'),

path('logout',user_logout,name='logout'),

path('web_login',web_login,name='web_login'),

path('user_otp/<int:pk>',user_otp,name='user_otp'),

path('home',home,name='home'),

path('web_logout',web_logout,name='web_logout'),

]

chopstick/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('',views.home,name="home"),
    path('dishes/', include('dishes.urls')),
    path('food_section/', include('food_section.urls')),
    path('customer/', include('customer.urls')),
    path('orders/', include('orders.urls')),
    path('outlet/', include('outlet.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import include, path
from customer.views import *

app_name = 'customer'

urlpatterns = [
path('customer_master',customer_master,name='customer_master'),

# path('add_new_customer',add_new_customer,name='add_new_customer'),

path('update_customer/<int:pk>/<int:pk1>',update_customer,name='update_customer'),

path('customer_detail/<int:pk>/<int:pk1>',customer_detail,name='customer_detail'),

path('delete_order/<int:pk>/<int:pk1>',delete_order,name='delete_order'),

]

dishes/urls.py
from django.urls import include, path
from dishes.views import *

app_name = 'dishes'

urlpatterns = [
path('all_dishes/<int:pk>/<int:pk1>',all_dishes,name='all_dishes'),

path('menu/<int:pk>',menu,name='menu'),

path('add_dishes/<int:pk>/<int:pk1>',add_dishes,name='add_dishes'),

path('update_dish/<int:pk>/<int:pk1>/<int:pk2>',update_dish,name='update_dish'),

path('delete_dish/<int:pk>/<int:pk1>/<int:pk2>',delete_dish,name='delete_dish'),

]

orders/urls.py
from django.urls import include, path
from orders.views import *

app_name = 'orders'

urlpatterns = [

path('select_order_item/<int:pk>',select_order_item,name='select_order_item'),

path('order_placed/<int:pk>',order_placed,name='order_placed'),

path('success_order/<int:pk>',success_order,name='success_order'),


path('order_master/<int:pk>',order_master,name='order_master'),

path('cust_order_details',cust_order_details,name='cust_order_details'),

path('order_cancle/<int:pk>',order_cancle,name='order_cancle'),

path('today_order/<int:pk>',today_order,name='today_order'),

path('update_status/<int:pk>/<int:pk1>',update_status,name='update_status'),

path('new_order/<int:pk>',new_order,name='new_order'),

path('order_details/<int:pk>/<int:pk1>',order_details,name='order_details'),

path('get_customer_detail',get_customer_detail,name='get_customer_detail'),

path('existing_order_update/<int:pk>/<int:pk1>',existing_order_update,name='existing_order_update'),

path('add_new_items_existing_order/<int:pk>/<int:pk1>',add_new_items_existing_order,name='add_new_items_existing_order'),

path('add_new_order_submit/<int:pk>',add_new_order_submit,name='add_new_order_submit'),

path('delete_one_item_from_order/<int:pk>/<int:pk1>',delete_one_item_from_order,name='delete_one_item_from_order'),
]

outlet/urls.py
from django.urls import include, path
from outlet.views import *

app_name = 'outlet'

urlpatterns = [

path('outlet_master',outlet_master,name='outlet_master'),

path('add_outlet',add_outlet,name='add_outlet'),

path('delete_outlet/<int:pk>',delete_outlet,name='delete_outlet'),

]

templates/dashboard/base.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lexend+Peta&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Magra:wght@700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">

    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>


    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Chopsticks Dashboard</title>
    {% block stylesheets %}
    {% endblock stylesheets %}

    {% block headscript %}
    {% endblock headscript %}
</head>

<body>
    <div class="main-section">
        <div class="navbar-div-main">
            <div class="header-logo-div">
                <div class="header-logo">
                    <img src="{% static 'images/logo1.png' %}" class="d-inline-block">
                </div>
            </div>
            <div class="sidemenu-items-div-main">
                <div class="outlet-div">
                    <div class="form-group">
                        <select class="form-control form-control-sm radius" style="font-weight:bold;" onchange="location = this.value;">
                            <option value="">select outlet</option>
                            {% for one in location %}
                            <option value="{% url 'orders:today_order' one.pk %}">{{one.outlet_name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="sidemenu-item-div">
                    {% with request.resolver_match.url_name as url_name %}

                    <li class="menu-item-list"><a href="#">DASHBOARD</a></li>

                    <li class="menu-item-list  {% if url_name == 'all_dishes' %}menu-item-active{% endif %}"><a href="{% url 'dishes:all_dishes' outlet_objects.pk food_objects.pk %}">MENU</a></li>

                    <li class="menu-item-list {% if url_name == 'today_order' or url_name == 'order_master' or url_name == 'order_cancle' or url_name == 'order_details' or url_name == 'new_order' %}menu-item-active{% endif %}"><a href="{% url 'orders:today_order' outlet_objects.pk %}">ORDERS</a></li>

                    <li class="menu-item-list  {% if url_name == 'customer_master' or url_name == 'customer_detail' %}menu-item-active{% endif %}"><a href="{% url 'customer:customer_master' %}">CUSTOMERS</a></li>
                    
                    {% comment %} <li class="menu-item-list  {% if url_name == 'outlet_master' %}menu-item-active{% endif %}"><a href="{% url 'outlet:outlet_master' %}">OUTLET</a></li> {% endcomment %}

                    <li class="menu-item-list"><a href="#">REPORTS</a></li>

                    <li class="logout-menu"><a href="{% url 'accounts:logout' %}">LOGOUT</a></li>

                    {% endwith %}
                </div>
            </div>
        </div>
        <div class="body-main-div">
            {% block content %}

            {% endblock  %}
        </div>
    </div>

    {% block script %}
    {% endblock  %}

    {% block extrascript %}
    {% endblock  %}
</body>

</html>

templates/dashboard/web_dash.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Rancho&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Chopsticks</title>
    {% block stylesheets %}
    {% endblock stylesheets %}

    {% block headscript %}
    {% endblock headscript %}
</head>

<body>
    <div>
        <nav class="navbar navbar-expand-lg fixed-top navbar-light ">
            <a class=" " href="">
                <img src="{% static 'images/logo.png' %}" height="75" width="220" class="d-inline-block" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" id="myLinks12" >
                <span class="navbar-toggler-icon" onclick="myFunction12()"></span>
            </button>
            <div class="collapse navbar-collapse text-md-center text-center justify-content-end " id="navbarNav">
                <ul class="navbar-nav">
                    {% with request.resolver_match.url_name as url_name %}
                    <li class="nav-item ml-3  active">
                        <a class="nav-link " href="#"><span class="navb-links {% if url_name == 'menu' %}active-nav{% endif %}">MENU</span> </a>
                    </li>

                    <li class="nav-item ml-3 active">
                        <a class="nav-link" href="{% url 'orders:cust_order_details' %}"><span class="navb-links {% if url_name == 'cust_order_details' %}active-nav{% endif %}">MY ORDERS </span></a>
                    </li>
                    <li class="nav-item ml-3 active ">
                        <a class="nav-link " href="tel:022 251781804"><span class="navb-links">CALL LBS OUTLET</span> </a>
                    </li>
                    <li class="nav-item ml-3 active">
                        <a class="nav-link" href="tel:022 251171114"><span class="navb-links">CALL KAILASH OUTLET</span></a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item ml-3 active">
                        <a class="btn btn-sm logout-btn" href="{% url 'accounts:web_logout' %}"><span class="">LOGOUT</span></a>
                    </li>
                    {% endif %}
                    {% endwith %}
                </ul>
            </div>
        </nav>
    </div>

{% block content %}

{% endblock  %}


    {% block script %}
    {% endblock  %}

    {% block extrascript %}
    {% endblock  %}
<script>
function myFunction12() {
    var x = document.getElementById("myLinks12");

    if (x.style.backgroundColor === "#fff") {
        document.getElementById("myLinks12").style.backgroundColor = "fff";
    } else {
        document.getElementById("myLinks12").style.backgroundColor = "yellow";

    }
}

</script>
</body>
</html>